### PR TITLE
Proposes a few readability edits

### PR DESCRIPTION
**Pull request by LJWatson**
@michaelchampion it really is very well written. I've just made a very few proposed edits.

I decided against expanding the different acronyms (HTTPS, API etc.) because I think they are known to the audience, and expanding them would make the text harder to read not more understandable.

I hesitated over the following phrase and in the end did not change it because I thought the words might have been chosen quite carefully:
> the Web is for all humanity;

A more readable alternative would be:
>the Web is for everyone

### CODE REVIEW

**Comment by LJWatson** [comment]
Relates to #4

**Comment by michaelchampion** [comment]
Thanks Léonie!  The only one I question is “it has been a major catalyst for social change”  changed to “it has been a major cause of social change”.  A catalyst isn’t a cause, it’s a facilitator. 

But this distinction isn’t very important to the Vision.  Clearly the web has “caused” social change as well as “catalyzing “ it.  If simplifying the vocabulary makes the document more useful to a broader audience, that’s fine with me.   

Furthermore, your review made me re-think my idea of who the target audience is. I’ve assumed people who think about the web platform are “geeky”  and comfortable with concepts from the natural sciences.  Thus,  “catalysis” seemed like an appropriate word to use.  Your review implies that is questionable for the readers of this document.   

What do others think?

**Comment by LJWatson** [comment]
> Thanks Léonie! The only one I question is “it has been a major 
catalyst for social change” changed to “it has been a major cause of 
social change”. A catalyst
isn’t a cause, it’s a facilitator.

I dithered about this one too, for the reason you mention. On reflection 
I think catalyst is OK - the only other word I can think of is trigger 
and that isn't quite right either - not to mention it perhaps has 
connotations we'd rather not get to.

 > Furthermore, your review made me re-think my idea of who the target 
audience is. I’ve assumed people who think about the web platform are 
“geeky” and comfortable
with concepts from the natural sciences. Thus, “catalysis” seemed like 
an appropriate word to use. Your review implies that is questionable for 
the readers
of this document.

I agree with your assessment of the likely audience, but that isn't 
mutually exclusive with needing readability - someone with a computer 
science degree may still not have English as a first language, or may be 
Dyslexic etc.

So you're probably right that phrases like catalyst are OK since they'll 
likely be known to the intended audience, whereas phrases like 
cherry-picking are more vernacular and likely to cause difficulties - 
for example for someone on the Autistic spectrum who finds non-literal 
phrases hard to understand.

**Comment by michaelchampion** [comment]
Thanks again @LJWatson , "phrases like cherry-picking are more vernacular and likely to cause difficulties - for example for someone on the Autistic spectrum who finds non-literal phrases hard to understand" is a very important point that I need to internalize! 

As a way forward,I suggest merging the PR as is. "Catalyst" is also used in a non-literal sense here, so I'd be inclined to err on the side of caution and literal meaning for the moment.  We can probably make the language more vivid than "[the web] has been a major cause of social change” while maintaining clarity/accessibility, but that's probably not the most important point in the Vision build consensus on right now.

**Pull request merged**
